/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class CutterNodeUI extends View {
        public static  uiView:any ={"type":"View","props":{"y":0,"x":19,"width":38,"height":115,"anchorX":0.5},"compId":2,"child":[{"type":"Image","props":{"y":57,"x":19,"width":115,"skin":"img/cutter.png","rotation":90,"height":38,"anchorY":0.5,"anchorX":0.5},"compId":3}],"loadList":["img/cutter.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(CutterNodeUI.uiView);
        }
    }
    REG("ui.CutterNodeUI",CutterNodeUI);
    export class GameSceneUI extends Scene {
		public img_target:Laya.Image;
        public static  uiView:any ={"type":"Scene","props":{"width":720,"height":1600},"compId":2,"child":[{"type":"Image","props":{"y":470,"x":360,"var":"img_target","skin":"img/target.png","anchorY":0.5,"anchorX":0.5},"compId":3}],"loadList":["img/target.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(GameSceneUI.uiView);
        }
    }
    REG("ui.GameSceneUI",GameSceneUI);
    export class goldViewUI extends View {
		public img_bg:Laya.Image;
		public icon_gold:Laya.Image;
		public label_dmd:Laya.FontClip;
        public static  uiView:any ={"type":"View","props":{"width":220,"height":70},"compId":2,"child":[{"type":"Image","props":{"y":35,"x":110,"width":220,"var":"img_bg","sizeGrid":"0,79,0,81","height":64,"anchorY":0.5,"anchorX":0.5},"compId":4},{"type":"Image","props":{"y":35,"x":30,"var":"icon_gold","anchorY":0.5,"anchorX":0.5},"compId":5},{"type":"FontClip","props":{"y":35,"x":103,"var":"label_dmd","value":"33","sheet":"1234567890","anchorY":0.5,"anchorX":0.3},"compId":6}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(goldViewUI.uiView);
        }
    }
    REG("ui.goldViewUI",goldViewUI);
    export class HallSceneUI extends Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":720,"height":1600},"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(HallSceneUI.uiView);
        }
    }
    REG("ui.HallSceneUI",HallSceneUI);
    export class LoadViewUI extends Scene {
		public img_bg:Laya.Image;
		public label_loadtext:Laya.Label;
		public img_prg1:Laya.Image;
		public img_prg2:Laya.Image;
		public img_logo:Laya.Image;
        public static  uiView:any ={"type":"Scene","props":{"width":720,"height":1280},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"width":720,"var":"img_bg","skin":"loading/img_loading_bg.png","height":1600},"compId":16},{"type":"Label","props":{"y":1058,"x":360,"var":"label_loadtext","text":"资源加载中,请稍后！","fontSize":36,"font":"Microsoft YaHei","color":"#ffffff","bold":true,"anchorY":0.5,"anchorX":0.5},"compId":3},{"type":"Image","props":{"y":947,"x":135,"width":450,"var":"img_prg1","skin":"loading/img_jdt_bg.png","sizeGrid":"16,90,18,50"},"compId":18},{"type":"Image","props":{"y":951,"x":141,"width":438,"var":"img_prg2","skin":"loading/img_jdt.png","sizeGrid":"16,53,11,38","height":40},"compId":19},{"type":"Image","props":{"y":499,"x":360,"var":"img_logo","skin":"loading/img_logo.png","anchorY":0.5,"anchorX":0.5},"compId":33}],"loadList":["loading/img_loading_bg.png","loading/img_jdt_bg.png","loading/img_jdt.png","loading/img_logo.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadViewUI.uiView);
        }
    }
    REG("ui.LoadViewUI",LoadViewUI);
    export class TipViewUI extends View {
		public tip_label:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"width":720,"height":100},"compId":2,"child":[{"type":"Box","props":{"y":0,"x":0,"width":720,"height":100,"bgColor":"#000000","alpha":0.7},"compId":5},{"type":"Label","props":{"y":50,"x":360,"var":"tip_label","text":"label","fontSize":30,"font":"SimHei","color":"#ffffff","anchorY":0.5,"anchorX":0.5},"compId":3}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(TipViewUI.uiView);
        }
    }
    REG("ui.TipViewUI",TipViewUI);
    export class ttPushUI extends View {
		public shareBox:Laya.Box;
		public share:Laya.Image;
		public btn_bgShare:Laya.Image;
		public btn_video:Laya.Image;
		public btn_share:Laya.Image;
		public hide_share:Laya.Image;
        public static  uiView:any ={"type":"View","props":{"zOrder":1000,"width":720,"visible":false,"mouseThrough":true,"hitTestPrior":false,"height":1280},"compId":2,"child":[{"type":"Box","props":{"visible":false,"var":"shareBox"},"compId":65,"child":[{"type":"Box","props":{"width":720,"height":1600,"bgColor":"#000000","alpha":0.8},"compId":66},{"type":"Image","props":{"y":300,"x":42,"var":"share","skin":"push/img_share_bg.png","scaleY":0.9,"scaleX":0.9},"compId":46,"child":[{"type":"Image","props":{"y":108,"x":56,"width":600,"var":"btn_bgShare","skin":"push/bg_share.png","height":300},"compId":72},{"type":"Image","props":{"y":160,"x":262,"var":"btn_video","skin":"push/img_play.png"},"compId":67},{"type":"Image","props":{"y":414,"x":300,"skin":"img/img_gold.png"},"compId":70},{"type":"Label","props":{"y":424,"x":360,"text":"+200","fontSize":36,"font":"SimSun","color":"#fff","bold":true},"compId":71},{"type":"Image","props":{"y":541,"x":201,"var":"btn_share","skin":"img/btn_yellow.png"},"compId":48,"child":[{"type":"Sprite","props":{"y":32,"x":49,"texture":"img/txt_7.png"},"compId":69}]},{"type":"Image","props":{"y":670,"x":285,"var":"hide_share","skin":"push/txt_nothanks.png"},"compId":68}]}]}],"loadList":["push/img_share_bg.png","push/bg_share.png","push/img_play.png","img/img_gold.png","img/btn_yellow.png","img/txt_7.png","push/txt_nothanks.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(ttPushUI.uiView);
        }
    }
    REG("ui.ttPushUI",ttPushUI);
}